# LiveKit Meet Docker Compose Configuration
# 使用客户端录制，不再需要 Egress 和 Redis 服务

services:
  livekit-server:
    image: livekit/livekit-server:latest
    container_name: livekit-server
    ports:
      - "7880:7880"      # WebSocket/HTTP API
      - "7881:7881"      # TCP for WebRTC
      - "50000-50100:50000-50100/udp"  # UDP range for WebRTC media
    volumes:
      - ./livekit-config/livekit.yaml:/etc/livekit.yaml:ro
    environment:
      - LIVEKIT_CONFIG_FILE=/etc/livekit.yaml
    command: ["--config", "/etc/livekit.yaml"]
    restart: unless-stopped
    networks:
      - livekit-network

  # MinIO - S3兼容的对象存储，用于保存录制文件
  minio:
    image: minio/minio:latest
    container_name: livekit-minio
    restart: unless-stopped
    ports:
      - "9000:9000"   # API端口
      - "9001:9001"   # Web控制台端口
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DEFAULT_BUCKETS=livekit-recordings:public
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - livekit-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio_data:

networks:
  livekit-network:
    driver: bridge
